### ISSUE TITLE
Username does not default to Wercker

### ISSUE THREAD

**Issue by drewfranklin** [wantedly/step-pretty-slack-notify#40] opened 2016-11-29 22:29 UTC
In the slack notification the username does not default to Wercker. It looks like environment variable WERCKER_PRETTY_SLACK_NOTIFY_USERNAME is not being defined in script/run, but I am not exactly sure if that is the issue

![screen shot 2016-11-29 at 2 26 32 pm](https://cloud.githubusercontent.com/assets/7517/20731601/e6b6082c-b63f-11e6-8071-9dcd0f71e4a7.png)

**Comment by spesnova** [comment] 2016-11-30 05:39
@drewfranklin Thank you for reporting.
Could you show me your `wercker.yml` ? I might be able to help you.

**Comment by drewfranklin** [comment] 2016-11-30 18:16
For sure
`box: zdfs/docker-suit
build:
  steps:
    - npm-install
    - script:
        name: create empty 'public' and 'deploy' directories
        code: |-
          mkdir 'public'
          mkdir 'deploy'
    - grunt:
        tasks: predeploy
    - grunt:
        tasks: deploy
    - script:
        name: copy documentation for deployment
        code: |-
          cp --recursive deploy/* "$WERCKER_OUTPUT_DIR"
    - script:
        name: echo nodejs information
        code: |
          echo "node version $(node -v) running"
          echo "npm version $(npm -v) running"
  after-steps:
    - wantedly/pretty-slack-notify:
        webhook_url: $SLACK_WEBHOOK_URL
        channel: suit
        notify_on: "failed"
deploy:
  steps:
    - duleorlovic/ftp-deploy:
        destination: ftp://$HOSTNAME/$FTP_TARGET
        username: $FTP_USERNAME
        password: $FTP_PASSWORD
  after-steps:
    - wantedly/pretty-slack-notify:
        webhook_url: $SLACK_WEBHOOK_URL
        channel: suit
deploy-release:
  steps:
    - duleorlovic/ftp-deploy:
        destination: ftp://$HOSTNAME/$WERCKER_GIT_BRANCH
        username: $FTP_USERNAME
        password: $FTP_PASSWORD
  after-steps:
    - wantedly/pretty-slack-notify:
        webhook_url: $SLACK_WEBHOOK_URL
        channel: suit
`

**Comment by spesnova** [comment] 2016-12-01 05:44
@drewfranklin Thank you for sharing it to me.

At first, you might be able to work around by specifying `username` option like this:

```yaml
        - wantedly/pretty-slack-notify:
            webhook_url: $SLACK_WEBHOOK_URL
            channel: suit
            username: Wercker
```

To find the root cause, could you show me  "wantedly/pretty-slack-notify" step's log on wercker?

**Comment by drewfranklin** [comment] 2016-12-01 18:34
Awesome thanks for the quick fix
Here is my log
![screen shot 2016-12-01 at 10 32 51 am](https://cloud.githubusercontent.com/assets/7517/20806922/ab927942-b7b1-11e6-8dc7-64574d2c5d67.png)

**Comment by spesnova** [comment] 2016-12-02 05:58
@drewfranklin Thanks! I could find the root cause from your log ❗️ 
This is a bug that empty username is set as default. And this bug will be fixed in next release 😃  
So please use `username` option to workaround until next version released.

**Closed** 2016-12-02 06:53 UTC

**Comment by dtan4** [comment] 2016-12-05 08:29
@drewfranklin step-pretty-slack-notify v0.3.4 including the fix of this issue was just released. Please try it.

**Comment by drewfranklin** [comment] 2016-12-07 19:24
Yep it worked thanks so much everyone!
